### ISSUE TITLE
Неправильно определяется местоположение

### ISSUE THREAD

**Issue by ruvasik** [Limych/ha-narodmon#119]
Supervisor 2023.11.1

На минимальную конфигурацию сервис присылает ответ с городом, который определяется по IP, а не по адресу в HA.
Даже если передаю в конфигурации координаты - ответ не меняется

```
narodmon:
  verify_ssl: false
  devices:
    - name: "Home"
      latitude: ##
      longitude: ##
      scan_interval: "00:30"
      sensors:
        - temperature
        - humidity
        - pressure
        - uv
        - pm
```

```
2023-11-12 16:07:44.701 DEBUG (MainThread) [custom_components.narodmon] Request: '{'cmd': 'appInit', 'version': '2.0.3', 'platform': '2023.10', 'uuid': 'a23fd71b9d064facb1fd83fcab9757cd'}'
2023-11-12 16:07:44.896 DEBUG (MainThread) [custom_components.narodmon] Response: '{"login":"","vip":0,"uid":0,"lat":47.2361,"lon":39.7189,"addr":"Rostov-on-Don, Rostov Region, Russia","url":null,"latest":null,"favorites":[],"types":[{"type":1,"name":"t air","unit":"°"},{"type":24,"name":"t water","unit":"°"},{"type":25,"name":"t soil","unit":"°"},{"type":21,"name":"t точка роси","unit":"°"},{"type":2,"name":"RH humidity","unit":"%"},{"type":3,"name":"atm.pressure","unit":"mmHg"},{"type":11,"name":"luminosity","unit":"Lx"},{"type":20,"name":"UV Index","unit":""},{"type":12,"name":"radiation","unit":"µR/h"},{"type":9,"name":"rainfall","unit":"mm"},{"type":22,"name":"dustiness","unit":"µg/m3"},{"type":4,"name":"speed","unit":"m/s"},{"type":5,"name":"direction","unit":"°"},{"type":15,"name":"concentration","unit":"ppm"},{"type":6,"name":"P power","unit":"W"},{"type":13,"name":"U voltage","unit":"V"},{"type":14,"name":"I current","unit":"A"},{"type":8,"name":"A energy","unit":"KWh"},{"type":19,"name":"% battery","unit":"%"},{"type":7,"name":"Rx,Tx traffic","unit":"Kbps"},{"type":10,"name":"logical","unit":""},{"type":16,"name":"dBm signal","unit":"dBm"},{"type":17,"name":"water meter","unit":"m3"},{"type":18,"name":"uptime","unit":"s"},{"type":255,"name":"numeric","unit":""},{"type":23,"name":"text type","unit":""}],"timestamp":1699794464}'
```
