### ISSUE TITLE
Ошибки при > 1 локации

### ISSUE THREAD

**Issue by ildar170975** [Limych/ha-narodmon#128]
## System Information

version | core-2024.5.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 5.10.0-16-amd64
arch | x86_64
timezone | Europe/Moscow
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1414
Downloaded Repositories | 54
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | pending
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 16
-- | --
resources | 39
views | 465
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 5, 2024 at 01:14
-- | --
current_recorder_run | May 15, 2024 at 03:48
estimated_db_size | 550.33 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-narodmon/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

Выбрал две локации с несколькими показателями:

![изображение](https://github.com/Limych/ha-narodmon/assets/71872483/dbc75e55-1429-4cc3-8013-91df44ebad4d)

![изображение](https://github.com/Limych/ha-narodmon/assets/71872483/b4e60ded-d75c-4470-81f7-178535cc77ec)

Код:
```
narodmon:
  timeout: 120
  verify_ssl: false
  devices:

    - name: Narodmon 1
      latitude: 55.899418
      longitude: 37.619291
      sensors:
        - temperature
        - humidity
        - pressure

    - name: Narodmon 2
      latitude: 55.906041
      longitude: 37.551907
      sensors:
        - temperature
        - pressure
```
Ошибки при старте HA:
2024-05-15 03:49:25.134 ERROR (MainThread) [custom_components.narodmon] Error fetching information from https://narodmon.com/api - Cannot connect to host narodmon.com:443 ssl:default [None]
2024-05-15 03:49:25.135 ERROR (MainThread) [custom_components.narodmon] Error fetching narodmon data:
2024-05-15 03:53:47.153 ERROR (MainThread) [custom_components.narodmon] Error fetching narodmon data:

Результат:

![изображение](https://github.com/Limych/ha-narodmon/assets/71872483/4fb1c48b-d148-49b2-bdb6-e9235f8a5fa1)

Иногда удается получить значения, но в большинстве случаев данные `unavailable`.

### Reproduction steps

см. выше

### Debug logs

```text
см. выше
```
