### ISSUE TITLE
Unexpected error fetching narodmon data

### ISSUE THREAD

**Issue by Gatses** [Limych/ha-narodmon#157]
### System Health details

Версия | core-2025.4.2
-- | --
Тип установки | Home Assistant Supervised
Среда разработки | false
Supervisor | true
Docker | true
Виртуальное окружение | false
Версия Python | 3.13.2
Семейство операционных систем | Linux
Версия операционной системы | 6.6.51+rpt-rpi-v8
Архитектура ЦП | aarch64
Часовой пояс | Europe/Moscow
Каталог конфигурации | /config

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4999
Installed Version | 2.0.5
Stage | running
Available Repositories | 1656
Downloaded Repositories | 34

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-narodmon/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

Добрый день!

В configuration.yaml следующие настройки:
```
narodmon:
  devices:
    - name: "Narodmon"
      sensors:
        - temperature
        - humidity
        - pressure
        - wind_speed
        - wind_bearing
        - precipitation
        - illuminance
        - radiation
        - uv
        - pm
```

Периодически в логах возникает следующая ошибка:
```
Unexpected error fetching narodmon data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/narodmon/__init__.py", line 221, in _async_update_data
    tps.remove(sensor["type"])
    ~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 3
```

### Reproduction steps

-

### Debug logs

```text
-
```
